### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ape-report** [chrismiceli/motp#8]
Reproduce:

1. Select `HOTP`.
2. Input profile name, e.g., `abcd`
3. Click `add Profile`

```
// java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=2
//  at java.lang.String.startEndAndLength(String.java:298)
//  at java.lang.String.substring(String.java:1087)
//  at org.cry.otp.ProfileSetup$2.onClick(ProfileSetup.java:73)
//  at android.view.View.performClick(View.java:5204)
//  at android.view.View$PerformClick.run(View.java:21153)
//  at android.os.Handler.handleCallback(Handler.java:739)
//  at android.os.Handler.dispatchMessage(Handler.java:95)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by chrismiceli** [comment]
Will be fixed in next release
