### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by ape-report** [chrismiceli/motp#9]
1. Add `HTOP`.
2. Leave `DIGITS` empty.
3. Clear `ADD PROFILE`.

```
// java.lang.NumberFormatException: Invalid int: ""
//  at java.lang.Integer.invalidInt(Integer.java:138)
//  at java.lang.Integer.parseInt(Integer.java:358)
//  at java.lang.Integer.parseInt(Integer.java:334)
//  at org.cry.otp.ProfileSetup$2.onClick(ProfileSetup.java:66)
//  at android.view.View.performClick(View.java:5204)
//  at android.view.View$PerformClick.run(View.java:21153)
//  at android.os.Handler.handleCallback(Handler.java:739)
//  at android.os.Handler.dispatchMessage(Handler.java:95)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by chrismiceli** [comment]
Will be fixed in next release.
